name: TEST CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub에서 자동 생성되는 토큰 사용
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Vercel API 토큰
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}  # Vercel 조직 ID
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}  # Vercel 프로젝트 ID
